# Generated by Django 2.1.2 on 2019-01-19 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lotte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lottery_date', models.DateField()),
                ('nubmer1', models.IntegerField()),
                ('nubmer2', models.IntegerField()),
                ('nubmer3', models.IntegerField()),
                ('nubmer4', models.IntegerField()),
                ('nubmer5', models.IntegerField()),
                ('nubmer6', models.IntegerField()),
            ],
        ),
    ]
