# Generated by Django 2.1.2 on 2019-01-19 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lotte', '0002_lotte_bonus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lotte',
            old_name='nubmer1',
            new_name='number1',
        ),
        migrations.RenameField(
            model_name='lotte',
            old_name='nubmer2',
            new_name='number2',
        ),
        migrations.RenameField(
            model_name='lotte',
            old_name='nubmer3',
            new_name='number3',
        ),
        migrations.RenameField(
            model_name='lotte',
            old_name='nubmer4',
            new_name='number4',
        ),
        migrations.RenameField(
            model_name='lotte',
            old_name='nubmer5',
            new_name='number5',
        ),
        migrations.RenameField(
            model_name='lotte',
            old_name='nubmer6',
            new_name='number6',
        ),
    ]
