# Generated by Django 2.1.2 on 2019-01-19 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotte', '0003_auto_20190120_0208'),
    ]

    operations = [
        migrations.AddField(
            model_name='lotte',
            name='number_set',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
