# Generated by Django 2.1.2 on 2019-01-11 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0002_auto_20190108_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='file',
            field=models.FileField(blank=True, default='', upload_to=''),
        ),
    ]
